name: Create or update branch and pull request from APG trigger

on:
  workflow_dispatch:
    inputs:
      apg_branch:
        description: 'Name of branch to be created'
        required: true
      apg_sha:
        description: 'Commit SHA to look for from source'
        required: true
      apg_pr_number:
        description: 'PR number from aria-practices that triggered this workflow'
        required: true
      fork_path:
        description: 'Available when the triggering PR is from a fork'
        required: false

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Get current job and log url
        uses: Tiryoh/gha-jobid-action@v1
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: create-pr

      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: scripts/pre-build/package-lock.json

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Conditionally define fork's username if exists
        run: |
          if [ -n "${{ github.event.inputs.fork_path }}" ] && [ "${{ github.event.inputs.fork_path }}" != 'false' ]; then
            FORK_USERNAME=$(echo "${{ github.event.inputs.fork_path }}" | cut -d'/' -f1)
            if [ "$FORK_USERNAME" != "${{ github.repository_owner }}" ]; then
              echo "FORK_USERNAME=$FORK_USERNAME" >> "$GITHUB_ENV"
              echo "FORK_USERNAME is set to: $FORK_USERNAME"
            else
              echo "FORK_USERNAME is equal to repository owner (${FORK_USERNAME}), skipping GITHUB_ENV assignment."
            fi
          else
            echo "Invalid fork_path, skipping FORK_USERNAME assignment."
          fi

      - name: Update git submodules
        run: |
          git submodule update --recursive --remote
          cd _external/aria-practices
          
          if [ -n "${{ github.event.inputs.fork_path }}" ] && [ "${{ github.event.inputs.fork_path }}" != 'false' ]; then
            echo "Found fork: ${{ github.event.inputs.fork_path }}"
            git remote add fork https://github.com/${{ github.event.inputs.fork_path }}.git
            git fetch fork
          fi
          
          git checkout ${{ github.event.inputs.apg_sha }}

      - name: Switch to and create/update branch
        id: switch_branch
        run: |
          # get the username from fork_path
          if [ -n "${{ github.event.inputs.fork_path }}" ] && [ "${{ github.event.inputs.fork_path }}" != 'false' ] && [ -n "$FORK_USERNAME" ]; then
             WAI_APG_BRANCH_NAME="apg/${FORK_USERNAME}-${{ github.event.inputs.apg_branch }}"
          else
            WAI_APG_BRANCH_NAME="apg/${{ github.event.inputs.apg_branch }}"
          fi
          
          # switch to branch if exists or create branch; format will be "apg/({username}-?){branch_name}"
          git switch "$WAI_APG_BRANCH_NAME" 2>/dev/null || git switch -c "$WAI_APG_BRANCH_NAME"
          
          echo "WAI_APG_BRANCH_NAME=$WAI_APG_BRANCH_NAME" >> "$GITHUB_OUTPUT"

      - name: Force rebase switched branch onto main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase --force-rebase origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update site files
        id: update_site_files
        working-directory: ./
        run: |
          bundle install
          npm install -C scripts/pre-build
          node ./scripts/pre-build
        continue-on-error: true

      - name: Commit changed files and submodule updates
        if: steps.update_site_files.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: "chore: Update branch with latest `${{ github.event.inputs.apg_branch }}` changes and submodule updates"
          branch: ${{ steps.switch_branch.outputs.WAI_APG_BRANCH_NAME }}
          push_options: '--force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update pull request
        working-directory: ./
        run: |
          set -e
          npm install -C scripts/create-pr
          node ./scripts/create-pr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APG_SHA: ${{ github.event.inputs.apg_sha }}
          APG_BRANCH: ${{ steps.switch_branch.outputs.WAI_APG_BRANCH_NAME }}
          APG_PR_NUMBER: ${{ github.event.inputs.apg_pr_number }}
          REPO_OWNER: ${{ github.repository_owner }}
          OUTCOME: ${{ steps.update_site_files.outcome }}
          JOB_ID: ${{ steps.jobs.outputs.job_id }}
