name: Automatically create branch and pull request

on:
  workflow_dispatch:
    inputs:
      apg_branch:
        description: 'Name of branch to be created'
        required: true
      apg_sha:
        description: 'Commit SHA to look for from source'
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "APG Branch: ${{ github.event.inputs.apg_branch }}"
          echo "APG SHA: ${{ github.event.inputs.apg_sha }}"

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm
          cache-dependency-path: scripts/create-pull-request/package-lock.json

      - name: Set up Ruby 2.6.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.2
          bundler-cache: true

      - name: Update git submodules
        run: |
          git fetch --all
          git submodule update --recursive --remote
          cd _external/aria-practices
          git checkout ${{ github.event.inputs.apg_sha }}

      - name: Switch to and update or create branch
        run: |
          # switch to branch if exists or create branch
          git switch ${{ github.event.inputs.apg_branch }} 2>/dev/null || git switch -c ${{ github.event.inputs.apg_branch }}
          git pull origin ${{ github.event.inputs.apg_branch }}

      - name: Create Pull Request
        run: |
          npm install @octokit/rest
          node ./scripts/create-pull-request
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APG_BRANCH: ${{ github.event.inputs.apg_branch }}

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes
          branch: ${{ github.event.inputs.apg_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
