name: Remove branch cleanup

on:
  workflow_dispatch:
    inputs:
      apg_branch:
        description: 'Name of branch to be removed'
        required: true

jobs:
  remove-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch exists
        id: check_if_exists
        run: |
          OUTPUT=$(git ls-remote --heads https://github.com/howard-e/wai-aria-practices.git ${{ github.event.inputs.apg_branch }} | wc -l)
          echo "::set-output name=branch-exists::$(echo $OUTPUT)"
      - name: See check result
        run: "echo ${{ steps.check_if_exists.outputs.branch-exists }}"
      - name: Clean up generated branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: ${{ github.event.inputs.apg_branch }}
